// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded values to fix deployment issues as a quick fix
const SUPABASE_URL = 'https://hhqhoqwpebnmfuhwhllw.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhocWhvcXdwZWJubWZ1aHdobGx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxNDUzNjMsImV4cCI6MjA5MjcyMTM2M30.hmFlW7RHkQVY3iwxAekJQIGemsgbQpJegnW8gB8S0Wc';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
